//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeskMind.Plugin.PythonRunner.WPF.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Py_Edit_Copy {
            get {
                return ResourceManager.GetString("Py_Edit_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string Py_Edit_Cut {
            get {
                return ResourceManager.GetString("Py_Edit_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Py_Edit_Menu {
            get {
                return ResourceManager.GetString("Py_Edit_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Py_Edit_Paste {
            get {
                return ResourceManager.GetString("Py_Edit_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string Py_Edit_SelectAll {
            get {
                return ResourceManager.GetString("Py_Edit_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string Py_File_Menu {
            get {
                return ResourceManager.GetString("Py_File_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        public static string Py_File_NewFolder {
            get {
                return ResourceManager.GetString("Py_File_NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Metadata.
        /// </summary>
        public static string Py_File_SaveMetadata {
            get {
                return ResourceManager.GetString("Py_File_SaveMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Requirements.
        /// </summary>
        public static string Py_File_SaveRequirements {
            get {
                return ResourceManager.GetString("Py_File_SaveRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Script.
        /// </summary>
        public static string Py_File_SaveScript {
            get {
                return ResourceManager.GetString("Py_File_SaveScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Python Runner.
        /// </summary>
        public static string Py_Help_About {
            get {
                return ResourceManager.GetString("Py_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Py_Help_Menu {
            get {
                return ResourceManager.GetString("Py_Help_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Parameter.
        /// </summary>
        public static string Py_Metadata_AddParameter {
            get {
                return ResourceManager.GetString("Py_Metadata_AddParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Py_Metadata_Description {
            get {
                return ResourceManager.GetString("Py_Metadata_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function Name.
        /// </summary>
        public static string Py_Metadata_FunctionName {
            get {
                return ResourceManager.GetString("Py_Metadata_FunctionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Type.
        /// </summary>
        public static string Py_Metadata_OutputType {
            get {
                return ResourceManager.GetString("Py_Metadata_OutputType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string Py_Metadata_Parameters {
            get {
                return ResourceManager.GetString("Py_Metadata_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Py_Metadata_Remove {
            get {
                return ResourceManager.GetString("Py_Metadata_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Metadata.
        /// </summary>
        public static string Py_Metadata_SaveMetadata {
            get {
                return ResourceManager.GetString("Py_Metadata_SaveMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string Py_Run_Menu {
            get {
                return ResourceManager.GetString("Py_Run_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string Py_Run_Run {
            get {
                return ResourceManager.GetString("Py_Run_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string Py_Run_Validate {
            get {
                return ResourceManager.GetString("Py_Run_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active folder:.
        /// </summary>
        public static string Py_Side_ActiveFolder {
            get {
                return ResourceManager.GetString("Py_Side_ActiveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Py_Side_Add {
            get {
                return ResourceManager.GetString("Py_Side_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Py_Side_Delete {
            get {
                return ResourceManager.GetString("Py_Side_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata.
        /// </summary>
        public static string Py_Tab_Metadata {
            get {
                return ResourceManager.GetString("Py_Tab_Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirements.
        /// </summary>
        public static string Py_Tab_Requirements {
            get {
                return ResourceManager.GetString("Py_Tab_Requirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script.
        /// </summary>
        public static string Py_Tab_Script {
            get {
                return ResourceManager.GetString("Py_Tab_Script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string Py_Toolbar_Generate {
            get {
                return ResourceManager.GetString("Py_Toolbar_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reqs.
        /// </summary>
        public static string Py_Toolbar_Reqs {
            get {
                return ResourceManager.GetString("Py_Toolbar_Reqs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string Py_Toolbar_Run {
            get {
                return ResourceManager.GetString("Py_Toolbar_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Py_Toolbar_Save {
            get {
                return ResourceManager.GetString("Py_Toolbar_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string Py_Toolbar_Validate {
            get {
                return ResourceManager.GetString("Py_Toolbar_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Requirements.
        /// </summary>
        public static string Py_Tools_GenerateRequirements {
            get {
                return ResourceManager.GetString("Py_Tools_GenerateRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Py_Tools_Menu {
            get {
                return ResourceManager.GetString("Py_Tools_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate requirements from environment.
        /// </summary>
        public static string Py_Tooltip_GenerateRequirements {
            get {
                return ResourceManager.GetString("Py_Tooltip_GenerateRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save requirements.txt.
        /// </summary>
        public static string Py_Tooltip_SaveRequirements {
            get {
                return ResourceManager.GetString("Py_Tooltip_SaveRequirements", resourceCulture);
            }
        }
    }
}
