// <auto-generated />
namespace DeskMind.Plugins.Office.Resources {
 using System;
 using System.Reflection;
 
 [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ResXFileCodeGenerator", "4.0.0.0")]
 [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
 [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
 internal class PluginStrings {
 private static global::System.Resources.ResourceManager resourceMan;
 private static global::System.Globalization.CultureInfo resourceCulture;
 internal PluginStrings() { }
 [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
 internal static global::System.Resources.ResourceManager ResourceManager {
 get {
 if (object.ReferenceEquals(resourceMan, null)) {
 var temp = new global::System.Resources.ResourceManager("DeskMind.Plugins.Office.Resources.PluginStrings", typeof(PluginStrings).Assembly);
 resourceMan = temp;
 }
 return resourceMan;
 }
 }
 [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
 internal static global::System.Globalization.CultureInfo Culture {
 get { return resourceCulture; }
 set { resourceCulture = value; }
 }
 internal static string ExcelCell_Name => ResourceManager.GetString("ExcelCell_Name", resourceCulture);
 internal static string ExcelCell_Description => ResourceManager.GetString("ExcelCell_Description", resourceCulture);
 internal static string ExcelCell_Dependency_Com => ResourceManager.GetString("ExcelCell_Dependency_Com", resourceCulture);
 internal static string ExcelSheet_Name => ResourceManager.GetString("ExcelSheet_Name", resourceCulture);
 internal static string ExcelSheet_Description => ResourceManager.GetString("ExcelSheet_Description", resourceCulture);
 internal static string ExcelSheet_Dependency_Com => ResourceManager.GetString("ExcelSheet_Dependency_Com", resourceCulture);
 internal static string WordText_Name => ResourceManager.GetString("WordText_Name", resourceCulture);
 internal static string WordText_Description => ResourceManager.GetString("WordText_Description", resourceCulture);
 internal static string WordText_Dependency_Com => ResourceManager.GetString("WordText_Dependency_Com", resourceCulture);
 internal static string WordStructure_Name => ResourceManager.GetString("WordStructure_Name", resourceCulture);
 internal static string WordStructure_Description => ResourceManager.GetString("WordStructure_Description", resourceCulture);
 internal static string WordStructure_Dependency_Com => ResourceManager.GetString("WordStructure_Dependency_Com", resourceCulture);
 internal static string OutlookEmail_Name => ResourceManager.GetString("OutlookEmail_Name", resourceCulture);
 internal static string OutlookEmail_Description => ResourceManager.GetString("OutlookEmail_Description", resourceCulture);
 internal static string OutlookEmail_Dependency_Com => ResourceManager.GetString("OutlookEmail_Dependency_Com", resourceCulture);
 internal static string OutlookCalendar_Name => ResourceManager.GetString("OutlookCalendar_Name", resourceCulture);
 internal static string OutlookCalendar_Description => ResourceManager.GetString("OutlookCalendar_Description", resourceCulture);
 internal static string OutlookCalendar_Dependency_Com => ResourceManager.GetString("OutlookCalendar_Dependency_Com", resourceCulture);
 internal static string PowerPointPresentation_Name => ResourceManager.GetString("PowerPointPresentation_Name", resourceCulture);
 internal static string PowerPointPresentation_Description => ResourceManager.GetString("PowerPointPresentation_Description", resourceCulture);
 internal static string PowerPointPresentation_Dependency_Com => ResourceManager.GetString("PowerPointPresentation_Dependency_Com", resourceCulture);
 internal static string PowerPointSlide_Name => ResourceManager.GetString("PowerPointSlide_Name", resourceCulture);
 internal static string PowerPointSlide_Description => ResourceManager.GetString("PowerPointSlide_Description", resourceCulture);
 internal static string PowerPointSlide_Dependency_Com => ResourceManager.GetString("PowerPointSlide_Dependency_Com", resourceCulture);
 internal static string WebSearch_Name => ResourceManager.GetString("WebSearch_Name", resourceCulture);
 internal static string WebSearch_Description => ResourceManager.GetString("WebSearch_Description", resourceCulture);
 internal static string Common_Role_Admin => ResourceManager.GetString("Common_Role_Admin", resourceCulture);
 }
}
